# Site Info
title: Ralasun Blog
tagline: 'for every field of data science'
description: ''
baseurl: ""
url: "http://ralasun.github.io"
logo: '/public/logo.jpg'

# Site configurations
gems:
  - jekyll-paginate
  - jekyll-sitemap
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Seonhwa Lee
  description: <strong>한걸음씩</strong>, 그리고 <strong>꾸준히</strong> 나아가기
  image: /public/img/profile_v1.jpg # md5 hash of your email address
  contact: 
    linkedin:  https://www.linkedin.com/in/ralasun
    github:    https://github.com/ralasun
    email:     mailto:sunhwalsh91@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Posts: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/main_low.jpg
  caption: ""

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-166283746-1' # leave blank if you don't want google analytics
disqus_short_name: 'ralasun-github-io' # leave blank if you don't want disqus

